<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>Cntryl.Fitz.Abstractions</PackageId>
    <AssemblyName>Cntryl.Fitz.Abstractions</AssemblyName>
    <RootNamespace>Cntryl.Fitz.Abstractions</RootNamespace>
    <Description>Public contracts for Fitz .NET client abstractions.</Description>
    <Authors>Cntryl</Authors>
    <RepositoryUrl>https://github.com/cntryl/fitz-dotnet</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

</Project>
